### ISSUE TITLE
Footnote in CodeBlock

### ISSUE THREAD

**Issue by JanLoebel** [tivie/showdown-footnotes#2]
If you add following code to a document and use showdown-footnotes the footnote will be converted to a footnote, which should not happen or?

---

```
Any Code
[^inCodeFootnote]
```

[^inCodeFootnote]: This is a footnote

---

**Comment by tivie** [comment]
@thanks I will have a look into it as soon as possible

**Comment by tivie** [comment]
Fixed in #3
